const data = [
  {
    id: "1",
    nama: "Kabel Data ANKER Micro Usb",
    stok: {
      jml: 31,
      tipe: "pcs",
    },
    merk: "Anker",
    kategori: "Kabel Data",
    h_beli: 24600,
    h_jual: 30000,
    gambar: "no-preview.png",
    ukuran: "",
  },
  {
    id: "2",
    nama: "Kabel Data ANKER Micro Usb",
    stok: {
      jml: 32,
      tipe: "pcs",
    },
    merk: "Anker",
    kategori: "Kabel Data",
    h_beli: 24600,
    h_jual: 30000,
    gambar: "no-preview.png",
    ukuran: "",
  },
  {
    id: "3",
    nama: "Kabel Data ANKER Micro Usb",
    stok: {
      jml: 33,
      tipe: "pcs",
    },
    merk: "Anker",
    kategori: "Kabel Data",
    h_beli: 24600,
    h_jual: 30000,
    gambar: "no-preview.png",
    ukuran: "",
  },
  {
    id: "4",
    nama: "Kabel Data ANKER Micro Usb",
    stok: {
      jml: 34,
      tipe: "pcs",
    },
    merk: "Anker",
    kategori: "Kabel Data",
    h_beli: 24600,
    h_jual: 30000,
    gambar: "no-preview.png",
    ukuran: "",
  },
  {
    id: "5",
    nama: "Kabel Data ANKER Micro Usb",
    stok: {
      jml: 35,
      tipe: "pcs",
    },
    merk: "Anker",
    kategori: "Kabel Data",
    h_beli: 24600,
    h_jual: 30000,
    gambar: "no-preview.png",
    ukuran: "",
  },
  {
    id: "6",
    nama: "Kabel Data ANKER Micro Usb",
    stok: {
      jml: 36,
      tipe: "pcs",
    },
    merk: "Anker",
    kategori: "Kabel Data",
    h_beli: 24600,
    h_jual: 30000,
    gambar: "no-preview.png",
    ukuran: "",
  },
];

export default data;
